GitHub Actions: Adapt Freetalk compilation code to GHA syntax
Using printf instead of echo because echo has "-" parameters so it
cannot be safely used to print things which contain "-" potentially.

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -50,33 +50,35 @@ jobs:
         else
           echo "No changes at fred, not recompiling."
         fi
-
-# Compile and test Freetalk
-script:
-  - set -o errexit
-  - echo 'Checksums of dependencies:' ; sha256sum ../fred/build/output/*
-  # Don't allow Travis to override the low memory limit which our builder sets with a higher one.
-  - unset _JAVA_OPTIONS
-  - echo 'fred version:' ; java -classpath '../fred/build/output/freenet.jar' 'freenet.node.Version'
-  - rm -f ./gradlew
-  - |
-    if [ "$(tr -cd '[:digit:]' <<< "$TRAVIS_JDK_VERSION")" -lt 13 ] ; then # Java versions < 13
-      # Latest Gradle version as of 2021-06-14.
-      gradle wrapper --gradle-version 7.1
-    else
-      # As of 2020-08-06, Travis' gradle binary fails to run the "wrapper" command on Java 13 and
-      # above so we instead use the wrapper of fred to download a new version of itself.
-      # TODO: Code quality: Remove this workaround once the issue is fixed.
-      "$TRAVIS_BUILD_DIR"/../fred/gradlew wrapper --gradle-version 7.1
-    fi
-  - ./gradlew --version
-  # To test the Ant and Gradle builders against each other uncomment the following.
-  # (The scripts will use the ./gradlew we've installed so we can ensure the latest Gradle works.)
-  ## - tools/compare-gradle-jars-with-ant-jars
-  ## - tools/compare-gradle-tests-with-ant-tests
-  # Show stdout/stderr so random seeds of failed tests can be obtained by developers to
-  # reproduce failed test runs. Also prevents the 10 minute build timeout.
-  - FREETALK__SHOW_GRADLE_TEST_OUTPUT=1 ./gradlew clean test jar
+    
+    - name: Compile and test Freetalk
+      run: |
+        set -o errexit
+        echo 'Checksums of dependencies:' ; sha256sum ../fred/build/output/*
+        # Don't allow Travis to override the low memory limit which our builder sets with a higher one.
+        # FIXME: Inspect printf output to see if we even need to do this on GitHub Actions.
+        printf "%s\n" "$JAVA_OPTIONS"
+        unset _JAVA_OPTIONS
+        echo 'fred version:'
+        java -classpath '../fred/build/output/freenet.jar' 'freenet.node.Version'
+        rm -f ./gradlew
+        if [ "$(tr -cd '[:digit:]' <<< "$TRAVIS_JDK_VERSION")" -lt 13 ] ; then # Java versions < 13
+          # Latest Gradle version as of 2021-06-14.
+          gradle wrapper --gradle-version 7.1
+        else
+          # As of 2020-08-06, Travis' gradle binary fails to run the "wrapper" command on Java 13 and
+          # above so we instead use the wrapper of fred to download a new version of itself.
+          # TODO: Code quality: Remove this workaround once the issue is fixed.
+          "$TRAVIS_BUILD_DIR"/../fred/gradlew wrapper --gradle-version 7.1
+        fi
+        ./gradlew --version
+        # To test the Ant and Gradle builders against each other uncomment the following.
+        # (The scripts will use the ./gradlew we've installed so we can ensure the latest Gradle works.)
+        ## - tools/compare-gradle-jars-with-ant-jars
+        ## - tools/compare-gradle-tests-with-ant-tests
+        # Show stdout/stderr so random seeds of failed tests can be obtained by developers to
+        # reproduce failed test runs. Also prevents the 10 minute build timeout.
+        FREETALK__SHOW_GRADLE_TEST_OUTPUT=1 ./gradlew clean test jar
 
 jdk:
   # openjdk7: Not available anymore.
